### ISSUE TITLE
ChatCensor v2.0 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/ChatCensor#7]
ChatCensor v2.0 Upcoming Features:
- [x] Spam block
- [x] Caps block
- [ ] Possible UTF-8 support for bad words
- [x] Better bad word actions configurations (possible implementation of temp bans)
- [x] Fix _chatcensor.command_ permission nodes in plugin.yml

**Comment by Flavius12** [comment]
Done!
